PREFIX bsbm-inst: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/>
PREFIX bsbm: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT DISTINCT ?product ?label
WHERE { 
  ?product rdfs:label ?label .
  ?product a bsbm:Product .
  {
    ?product bsbm:productFeature bsbm-inst:ProductFeature1 .
    ?product bsbm:productFeature bsbm-inst:ProductFeature2 .
  } UNION {
    ?product bsbm:productFeature bsbm-inst:ProductFeature3 .
    ?product bsbm:productFeature bsbm-inst:ProductFeature4 .
  }
  ?product bsbm:productPropertyNumeric1 ?value1 .
  FILTER (?value1 > 100)
}
ORDER BY ?label
LIMIT 10 