#!/usr/bin/env node
/**
 * report.js — collapse a results JSON into the LaTeX table that
 * paper §8.3 ingests via \input{...}.
 *
 * Output path (relative to the workspace, when checked in):
 *   paper/sources/zkSPARQL-bench/analysis/out/table-8.3.tex
 *
 * The paper TeX should contain (when ready):
 *   \input{paper/sources/zkSPARQL-bench/analysis/out/table-8.3.tex}
 *
 * Usage:
 *   node analysis/report.js results/2026-05-04-bootstrap.json \
 *     --out analysis/out/table-8.3.tex
 *
 * This is a deliberately tiny pass — per
 * `feedback_paper_focus_over_completeness.md`, only the cells the
 * paper actually cites get rendered. Unsupported cells render as
 * the literal `n/a`.
 */

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

function parseArgs(argv) {
  const args = { input: null, out: null };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === '--out') args.out = argv[++i];
    else if (!args.input) args.input = a;
  }
  return args;
}

function fmtValue(row) {
  if (row.status === 'ok' && row.value != null) {
    if (row.cell.metric === 'proof-size-b') return `${row.value} B`;
    if (row.cell.metric.endsWith('-ms')) return `${row.value.toFixed(0)} ms`;
    return String(row.value);
  }
  return 'n/a';
}

function buildTable(report) {
  // Curated subset for §8.3 headline figure: prove-time only,
  // grouped by query, faceted by commitment, coloured by signature.
  const rows = report.rows.filter((r) => r.cell.metric === 'prove-time-ms');
  const queries = [...new Set(rows.map((r) => `${r.cell.queryClass}/${r.cell.query}`))].sort();
  const columns = [...new Set(rows.map((r) => `${r.cell.commitment} \\xspace ${r.cell.signature}`))].sort();

  const lookup = new Map();
  for (const r of rows) {
    const k = `${r.cell.queryClass}/${r.cell.query}|${r.cell.commitment} \\xspace ${r.cell.signature}|${r.cell.dataset}`;
    lookup.set(k, r);
  }

  // Single dataset for the headline table — pick LUBM-1 for the
  // bootstrap; the EC2 sweep generates a separate file per dataset.
  const dataset = 'LUBM-1';

  const lines = [];
  lines.push('% Auto-generated by analysis/report.js — do not hand-edit.');
  lines.push(`% Source: results commit ${report.provenance?.benchRepoCommit ?? 'unknown'}`);
  lines.push(`% sparql_noir commit ${report.provenance?.sparqlNoirCommit ?? 'unknown'}`);
  lines.push(`% Generated ${report.provenance?.date ?? new Date().toISOString()}`);
  lines.push('\\begin{tabular}{l' + 'r'.repeat(columns.length) + '}');
  lines.push('\\toprule');
  lines.push(['Query', ...columns].join(' & ') + ' \\\\');
  lines.push('\\midrule');
  for (const q of queries) {
    const cells = columns.map((col) => {
      const r = lookup.get(`${q}|${col}|${dataset}`);
      return r ? fmtValue(r) : 'n/a';
    });
    lines.push([q.replace(/_/g, '\\_'), ...cells].join(' & ') + ' \\\\');
  }
  lines.push('\\bottomrule');
  lines.push('\\end{tabular}');
  return lines.join('\n') + '\n';
}

function main() {
  const args = parseArgs(process.argv.slice(2));
  if (!args.input) {
    console.error('usage: report.js <results.json> [--out path.tex]');
    process.exit(2);
  }
  const report = JSON.parse(readFileSync(args.input, 'utf8'));
  const tex = buildTable(report);
  if (args.out) {
    const out = resolve(args.out);
    mkdirSync(dirname(out), { recursive: true });
    writeFileSync(out, tex);
    console.error(`[zkSPARQL-bench] wrote ${out}`);
  } else {
    process.stdout.write(tex);
  }
}

main();
